#
# Module manifest for module 'PMCTerminal'
#
# Generated by: Your Name
#
# Generated on: 2023-10-27
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PMCTerminal.psm1'

# Version number of this module.
ModuleVersion = '5.0.0'

# ID used to uniquely identify this module
GUID = 'd8f8a1b3-5c6d-4e9a-8b2c-1f7a6e5d4c3b'

# Author of this module
Author = 'Your Name'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Your Name. All rights reserved.'

# Description of the functionality provided by this module
Description = 'The complete PMC Terminal v5 application module.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

#
# The magic happens here. List all your .psm1 files.
# PowerShell will load them all automatically. Order does not matter.
#
NestedModules = @(
    '..\modules\exceptions.psm1'
    '..\modules\logger.psm1'
    '..\modules\event-system.psm1'
    '..\modules\theme-manager.psm1'
    '..\modules\models.psm1'
    '..\components\tui-primitives.psm1'
    '..\components\ui-classes.psm1'
    '..\layout\panels-class.psm1'
    '..\components\navigation-class.psm1'
    '..\components\advanced-data-components.psm1'
    '..\components\advanced-input-components.psm1'
    '..\components\tui-components.psm1'
    '..\modules\data-manager.psm1'
    '..\services\keybinding-service.psm1'
    '..\services\navigation-service-class.psm1'
    '..\modules\dialog-system-class.psm1'
    '..\modules\tui-framework.psm1'
    '..\screens\dashboard\dashboard-screen.psm1'
    '..\screens\task-list-screen.psm1'
    '..\modules\tui-engine.psm1'
)


# Functions to export from this module
FunctionsToExport = @(
    'Start-PMCTerminal'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with discoverability in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

}