#Requires -Version 7.0
# Auto-generated by Mushroom

Write-Host "Loading modules..." -ForegroundColor Gray

# Load in dependency order
$patterns = @(
    'lib/*.ps1',
    'modules/*.ps1',
    'services/*.ps1',
    'components/*.ps1',
    'screens/*.ps1'
)

foreach ($pattern in $patterns) {
    Get-ChildItem $pattern -ErrorAction SilentlyContinue | ForEach-Object {
        Write-Host "  Loading: $($_.Name)" -ForegroundColor DarkGray
        . $_.FullName
    }
}

Write-Host "Ready!" -ForegroundColor Green

# Call main if exists
if (Get-Command Start-Application -ErrorAction SilentlyContinue) {
    Start-Application
}
